### ISSUE TITLE
Gifs repeating

### ISSUE THREAD

**Issue by Johanna-hub** [fac-12/jnhc-apis#32]
Love the site and works great for me, just seeing a few of the gifs repeating, don't know if you mind that - we used random to generate a random image on ours

You could also look in the search terms you are using to make it more relevant and understandable to user (know we have to do that too!!)

**Comment by lexadecimals** [comment]
Re search terms, I would say if you can find terms that tend to bring up  very similar gifs that could help. Maybe think about words that show your response to a film such as "applause" or "disappointment" as opposed to the review word, if that makes sense? 

I'm nitpicking cos everything else is :thumbsup:

**Comment by carolineapp** [comment]
Thanks guys fixed!
